name: Python SAST with Bandit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit-sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit analysis
        run: |
          bandit -r .

      - name: Optimize output
        run: |
          bandit -r . -o bandit-report.txt -f txt

      - name: Upload Bandit report
        uses: actions/upload-artifact@v2
        with:
          name: bandit-report
          path: bandit-report.txt
