name: Bandit SAST Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r .
